"""Public puzzle-model API for the sliding-tile solver package."""

from .puzzle_state import (
    PuzzleState,
    create_goal_state,
    format_board,
    index_to_position,
    position_to_index,
)
from .search_support import (
    STATUS_INVALID,
    STATUS_NOT_SOLVED,
    STATUS_SOLVED,
    STATUS_UNSOLVABLE,
    ExpandedCounter,
    SearchResult,
    SearchStep,
    make_invalid_result,
    make_solved_result,
    make_unsolvable_result,
    reconstruct_path,
)
from .search import (
    ASTAR_MANHATTAN_ALGORITHM_NAME,
    ASTAR_MISPLACED_ALGORITHM_NAME,
    BFS_ALGORITHM_NAME,
    a_star_manhattan,
    a_star_misplaced,
    breadth_first_search,
)
from .constants import BLANK, DOWN, LEFT, MOVES, RIGHT, SUPPORTED_SIZES, UP
from .heuristics import manhattan_distance, misplaced_tiles
from .solvability import blank_row_from_bottom, count_inversions, is_solvable
from .validation import InvalidPuzzleStateError, ValidatedBoard, infer_size, validate_board
from .verification_cases import (
    COMPARISON_BFS_MINIMUM_LENGTH,
    COMPARISON_BOARD,
    COMPARISON_SEQUENCE_FROM_GOAL,
    INVALID_BOARD,
    ONE_MOVE_BFS_MINIMUM_LENGTH,
    ONE_MOVE_BOARD,
    ONE_MOVE_SEQUENCE_FROM_GOAL,
    SEVERAL_MOVE_BFS_MINIMUM_LENGTH,
    SEVERAL_MOVE_BOARD,
    SEVERAL_MOVE_SEQUENCE_FROM_GOAL,
    SOLVED_BOARD,
    UNSOLVABLE_BOARD,
    VERIFICATION_CASES,
    VERIFICATION_SIZE,
)

__all__ = [
    "BLANK",
    "DOWN",
    "LEFT",
    "MOVES",
    "RIGHT",
    "SUPPORTED_SIZES",
    "UP",
    "STATUS_INVALID",
    "STATUS_NOT_SOLVED",
    "STATUS_SOLVED",
    "STATUS_UNSOLVABLE",
    "ASTAR_MANHATTAN_ALGORITHM_NAME",
    "ASTAR_MISPLACED_ALGORITHM_NAME",
    "BFS_ALGORITHM_NAME",
    "COMPARISON_BFS_MINIMUM_LENGTH",
    "COMPARISON_BOARD",
    "COMPARISON_SEQUENCE_FROM_GOAL",
    "ExpandedCounter",
    "INVALID_BOARD",
    "ONE_MOVE_BFS_MINIMUM_LENGTH",
    "ONE_MOVE_BOARD",
    "ONE_MOVE_SEQUENCE_FROM_GOAL",
    "PuzzleState",
    "InvalidPuzzleStateError",
    "SearchResult",
    "SearchStep",
    "SEVERAL_MOVE_BFS_MINIMUM_LENGTH",
    "SEVERAL_MOVE_BOARD",
    "SEVERAL_MOVE_SEQUENCE_FROM_GOAL",
    "SOLVED_BOARD",
    "UNSOLVABLE_BOARD",
    "VERIFICATION_CASES",
    "VERIFICATION_SIZE",
    "ValidatedBoard",
    "a_star_manhattan",
    "a_star_misplaced",
    "blank_row_from_bottom",
    "breadth_first_search",
    "count_inversions",
    "create_goal_state",
    "format_board",
    "infer_size",
    "index_to_position",
    "is_solvable",
    "manhattan_distance",
    "make_invalid_result",
    "make_solved_result",
    "make_unsolvable_result",
    "misplaced_tiles",
    "position_to_index",
    "reconstruct_path",
    "validate_board",
]
